export const productsData = [
  {
    id: 1,
    name: "Voguish Fashionable Women Backpack",
    category: "Women Backpacks",
    price: 237,
    discountPrice: 263,
    rating: 3.9,
    reviews: 34,
    image: "https://img.etimg.com/thumb/width-1200,height-1200,imgsize-46384,resizemode-75,msid-94816712/top-trending-products/lifestyle/best-backpacks-for-women.jpg",
  },
  {
    id: 2,
    name: "Trendy Alluring Wallets",
    category: "Wallets",
    price: 142,
    discountPrice: null,
    rating: 3.7,
    reviews: 15388,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBEvqlW9QWsZ2DCx_fcIVwJ1ThQK5eVTMtOQ&s",
  },
  {
    id: 3,
    name: "Graceful Versatile Women Handbags",
    category: "Handbags",
    price: 232,
    discountPrice: null,
    rating: 4.0,
    reviews: 19193,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMy43ps5AOJHp45w3Q2oxdjavk6yCPvLUQ_w&s",
  },
  {
    id: 4,
    name: "Trendy Classy Sling Bags",
    category: "Slingbags",
    price: 243,
    discountPrice: null,
    rating: 4.0,
    reviews: 4831,
    image: "https://cdn.pixabay.com/photo/2017/05/30/08/33/handbag-2356179_640.jpg",
  },
  {
    id: 5,
    name: "Elegant Evening Clutch",
    category: "Clutches",
    price: 312,
    discountPrice: 349,
    rating: 4.2,
    reviews: 2123,
    image: "https://m.media-amazon.com/images/I/81ri5ajhuBL._AC_UY1000_.jpg",
  },
  {
    id: 6,
    name: "Classic Leather Wallet",
    category: "Wallets",
    price: 189,
    discountPrice: 219,
    rating: 4.5,
    reviews: 5823,
    image: "https://godbolegear.com/cdn/shop/files/Hand_Grained_Leather_Wallet_in_Chestnut_Leather.jpg?v=1717913883&width=1445",
  },
  {
    id: 7,
    name: "Stylish Cross Body Bag",
    category: "Cross Body Bags & Sling Bags",
    price: 349,
    discountPrice: 399,
    rating: 4.3,
    reviews: 8392,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 8,
    name: "Chic Potli Bag",
    category: "Potlis",
    price: 149,
    discountPrice: null,
    rating: 3.8,
    reviews: 1298,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 9,
    name: "Durable Travel Waist Bag",
    category: "Waist Bags",
    price: 210,
    discountPrice: 259,
    rating: 4.1,
    reviews: 2002,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 10,
    name: "Trendy Women's Backpack",
    category: "Women Backpacks",
    price: 279,
    discountPrice: 299,
    rating: 4.0,
    reviews: 4217,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 11,
    name: "Fashionable Sling Bag",
    category: "Slingbags",
    price: 199,
    discountPrice: null,
    rating: 3.9,
    reviews: 1834,
    image: "https://cdn.pixabay.com/photo/2017/05/30/08/33/handbag-2356179_640.jpg",
  },
  {
    id: 12,
    name: "Elegant Leather Handbag",
    category: "Handbags",
    price: 349,
    discountPrice: 399,
    rating: 4.6,
    reviews: 5427,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 13,
    name: "Casual Tote Bag",
    category: "Handbags",
    price: 299,
    discountPrice: 349,
    rating: 4.2,
    reviews: 2511,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 14,
    name: "Minimalist Coin Wallet",
    category: "Wallets",
    price: 79,
    discountPrice: 99,
    rating: 3.8,
    reviews: 931,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 15,
    name: "Luxury Evening Clutch",
    category: "Clutches",
    price: 450,
    discountPrice: 499,
    rating: 4.8,
    reviews: 1265,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 16,
    name: "Smart Office Backpack",
    category: "Women Backpacks",
    price: 399,
    discountPrice: 450,
    rating: 4.5,
    reviews: 2133,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 17,
    name: "Portable Mini Wallet",
    category: "Wallets",
    price: 95,
    discountPrice: null,
    rating: 3.9,
    reviews: 756,
    image: "https://cdn.pixabay.com/photo/2017/05/30/08/33/handbag-2356179_640.jpg",
  },
  {
    id: 18,
    name: "Sophisticated Sling Bag",
    category: "Slingbags",
    price: 210,
    discountPrice: 239,
    rating: 4.1,
    reviews: 1621,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 19,
    name: "Trendy Boho Potli Bag",
    category: "Potlis",
    price: 189,
    discountPrice: 219,
    rating: 4.0,
    reviews: 892,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 20,
    name: "Casual Crossbody Sling Bag",
    category: "Cross Body Bags & Sling Bags",
    price: 189,
    discountPrice: 219,
    rating: 4.0,
    reviews: 2833,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 21,
    name: "Luxurious Tote Bag",
    category: "Handbags",
    price: 410,
    discountPrice: 459,
    rating: 4.5,
    reviews: 3239,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 22,
    name: "Compact Travel Wallet",
    category: "Wallets",
    price: 119,
    discountPrice: 139,
    rating: 4.0,
    reviews: 1111,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 23,
    name: "Stylish Leather Clutch",
    category: "Clutches",
    price: 220,
    discountPrice: 249,
    rating: 4.2,
    reviews: 1456,
    image: "https://cdn.pixabay.com/photo/2017/05/30/08/33/handbag-2356179_640.jpg",
  },
  {
    id: 24,
    name: "Multi-functional Backpack",
    category: "Women Backpacks",
    price: 499,
    discountPrice: 549,
    rating: 4.7,
    reviews: 1943,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 25,
    name: "Classic Zipper Wallet",
    category: "Wallets",
    price: 179,
    discountPrice: 199,
    rating: 4.1,
    reviews: 2923,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 26,
    name: "Trendy Designer Handbag",
    category: "Handbags",
    price: 310,
    discountPrice: 359,
    rating: 4.3,
    reviews: 1829,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 27,
    name: "Elegant Evening Sling Bag",
    category: "Slingbags",
    price: 229,
    discountPrice: 259,
    rating: 4.4,
    reviews: 1443,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 28,
    name: "Stylish Women Backpack",
    category: "Women Backpacks",
    price: 289,
    discountPrice: 329,
    rating: 4.0,
    reviews: 1763,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 29,
    name: "Fashionable Shoulder Bag",
    category: "Handbags",
    price: 380,
    discountPrice: 429,
    rating: 4.6,
    reviews: 2103,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 30,
    name: "Leather Bi-fold Wallet",
    category: "Wallets",
    price: 159,
    discountPrice: 189,
    rating: 4.1,
    reviews: 2232,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 31,
    name: "Classic Tote Bag",
    category: "Handbags",
    price: 299,
    discountPrice: 349,
    rating: 4.3,
    reviews: 2511,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 32,
    name: "Voguish Sling Bag",
    category: "Slingbags",
    price: 249,
    discountPrice: 279,
    rating: 4.2,
    reviews: 1933,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 33,
    name: "Chic Leather Backpack",
    category: "Women Backpacks",
    price: 320,
    discountPrice: 370,
    rating: 4.4,
    reviews: 1892,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 34,
    name: "Compact Coin Wallet",
    category: "Wallets",
    price: 89,
    discountPrice: 109,
    rating: 3.9,
    reviews: 891,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  },
  {
    id: 35,
    name: "Luxury Leather Clutch",
    category: "Clutches",
    price: 399,
    discountPrice: 449,
    rating: 4.5,
    reviews: 1421,
    image: "https://cdn.pixabay.com/photo/2017/05/30/08/33/handbag-2356179_640.jpg",
  },
  {
    id: 36,
    name: "Stylish Leather Tote Bag",
    category: "Handbags",
    price: 379,
    discountPrice: 429,
    rating: 4.5,
    reviews: 2313,
    image: "https://m.media-amazon.com/images/I/81ucblRgQ4L._AC_UY1000_.jpg",
  }
];